
let x = 10
try {

    console.log(`Value of x is ${x}`)
}
catch(error) {
    console.log(error.message, ", Error")
}

